---
- hosts: all
  remote_user: vagrant
  vars_files:
    - ../base_vm/ansible/vars/default.yml
    - vars/oxideshop.yml
    - [../project.yml, vars/oxideshop.yml]
    - [~/.personal_ansible_vm.yml, ../project.yml, vars/oxideshop.yml]
    - [../personal.yml, ~/.personal_ansible_vm.yml, ../project.yml, vars/oxideshop.yml]
  roles:
    - common
